generate:
  lm_model: "gpt-4o-mini"
  output_length: 64
  num_of_examples: 72
  concept_path: "axbench/data/gemma-2-9b_20-gemmascope-res-16k.json"
  max_concepts: 10
  master_data_dir: "axbench/data"
  dataset_category: "instruction"
  lm_use_cache: false
  seed: 42
train:
  model_name: "google/gemma-2-9b-it"
  layer: 20
  component: "res"
  seed: 42
  use_bf16: true
  models:
    SFT:
      batch_size: 18
      gradient_accumulation_steps: 8
      n_epochs: 8
      lr: 0.00004
      weight_decay: 0.00
      binarize_dataset: false
      exclude_bos: true
inference:
  use_bf16: true
  # if you are verifying latent, you dont have to include steering models.
  models: ["SFT", "PromptSteering"]
  model_name: "google/gemma-2-9b-it"
  # latent related params
  output_length: 128
  latent_num_of_examples: 20
  latent_batch_size: 16
  # steering related params
  steering_intervention_type: "addition" # clamping
  steering_model_name: "google/gemma-2-9b-it"
  steering_datasets: ["AlpacaEval"]
  steering_batch_size: 5
  steering_output_length: 128
  steering_layers: [20]
  steering_num_of_examples: 20 # number of examples per concept and per factor
  steering_factors: [1.0] # number of steering factors per example
  # master data dir is shared across all jobs.
  master_data_dir: "axbench/data"
  seed: 42
  lm_model: "gpt-4o-mini"
  # generation related params
  temperature: 1.0