generate:
  lm_model: "gpt-4o-mini"
  output_length: 64
  num_of_examples: 72
  concept_path: "axbench/data/gemma-2-2b_20-gemmascope-res-16k.json"
  max_concepts: 500
  master_data_dir: "axbench/data"
  dataset_category: "instruction"
  lm_use_cache: false
  seed: 42
train:
  model_name: "google/gemma-2-2b-it"
  layer: 20
  component: "res"
  seed: 42
  use_bf16: true
  models:
    SparseLinearProbe:
      batch_size: 6
      gradient_accumulation_steps: 1
      n_epochs: 12
      lr: 0.008
      topk: 8
      coeff_latent_l1_loss: 0.005
      coeff_l1_loss: 0.00
      coeff_l2_loss: 0.02
      binarize_dataset: true
      low_rank_dimension: 1
    LsReFT:
      batch_size: 6
      gradient_accumulation_steps: 1
      n_epochs: 12
      lr: 0.008
      weight_decay: 0.00
      topk: 8
      coeff_latent_l1_loss: 0.005
      low_rank_dimension: 1
      intervention_positions: "all"
      intervention_type: "addition" # clamping
      binarize_dataset: false
      exclude_bos: true
    SteeringVector:
      batch_size: 6
      gradient_accumulation_steps: 1
      n_epochs: 12
      lr: 0.008
      weight_decay: 0.00
      low_rank_dimension: 1
      intervention_positions: "all"
      intervention_type: "addition" # clamping
      binarize_dataset: false
      exclude_bos: true
inference:
  use_bf16: true
  models: ["LsReFT", "SteeringVector", "SparseLinearProbe"]
  model_name: "google/gemma-2-2b-it"
  # latent related params
  output_length: 128
  latent_num_of_examples: 20
  latent_batch_size: 16
  # steering related params
  steering_intervention_type: "addition" # clamping
  steering_model_name: "google/gemma-2-2b-it"
  steering_datasets: ["AlpacaEval"]
  steering_batch_size: 10
  steering_output_length: 128
  steering_layers: [20]
  steering_num_of_examples: 10 # number of examples per concept and per factor
  steering_factors: [0.2, 0.4, 0.6, 0.8, 1.0, 1.2, 1.4, 1.6, 1.8, 2.0, 2.5, 3.0, 4.0, 5.0] # number of steering factors per example
  # master data dir is shared across all jobs.
  master_data_dir: "axbench/data"
  seed: 42
  lm_model: "gpt-4o-mini"
  # generation related params
  temperature: 1.0