generate:
  lm_model: "gpt-4o-mini"
  output_length: 64
  num_of_examples: 72
  concept_path: "axbench/data/gemma-2-2b_20-gemmascope-res-16k.json"
  max_concepts: 10
  master_data_dir: "axbench/data"
  dataset_category: "instruction"
  seed: 42

train:
  model_name: "google/gemma-2-2b-it"
  layer: 20
  component: "res"
  seed: 43
  use_bf16: true
  models:
    DiffMean:
      batch_size: 6
      n_epochs: 12
      binarize_dataset: true
      low_rank_dimension: 1

inference:
  use_bf16: true
  models: ["PromptSteering", "DiffMean"]
  model_name: "google/gemma-2-2b-it"
  # latent related params
  output_length: 128
  latent_num_of_examples: 36
  latent_batch_size: 16
  # steering related params
  steering_intervention_type: "addition" # clamping
  steering_model_name: "google/gemma-2-2b-it"
  steering_datasets: ["AlpacaEval"]
  steering_batch_size: 10
  steering_output_length: 128
  steering_layers: [20]
  steering_num_of_examples: 10 # number of examples per concept and per factor
  steering_factors: [0.5, 1.0, 1.5, 2.0, 2.5, 3.0, 3.5, 4.0, 4.5, 5.0] # number of steering factors per example
  # master data dir is shared across all jobs.
  master_data_dir: "axbench/data"
  seed: 43
  lm_model: "gpt-4o-mini"
  # generation related params
  temperature: 1.0

evaluate:
  models: ["PromptSteering", "DiffMean"]
  latent_evaluators: [
    "AUCROCEvaluator",
    "HardNegativeEvaluator",
  ]
  steering_evaluators: [
    "PerplexityEvaluator", 
    "LMJudgeEvaluator",
  ]
  winrate_split_ratio: 0.5 # this is for steering only, we use a separate partition for factor selection.
  # Number of processes to run in parallel for steering evaluation.
  num_of_workers: 32
  lm_model: "gpt-4o-mini"
  run_winrate: true
  winrate_baseline: "PromptSteering"
  # master data dir is shared across all jobs.
  master_data_dir: "axbench/data"

