generate:
  lm_model: "gpt-4o-mini"
  output_length: 128
  num_of_examples: 144
  concept_path: "axbench/data/llama3.1-8b_20-llamascope-res-131k.json"
  max_concepts: 16000
  master_data_dir: "axbench/data"
  dataset_category: "instruction"
  lm_use_cache: false
  seed: 42