generate:
  lm_model: "gpt-4o-mini"
  input_length: 32
  output_length: 32
  num_of_examples: 72
  concept_path: "axbench/data/gemma-2-2b_20-gemmascope-res-16k.json"
  max_concepts: 10
  master_data_dir: "axbench/data"
  dataset_category: "instruction"
  lm_use_cache: false
  seed: 42
  keep_orig_axbench_format: true
train:
  model_name: "google/gemma-2-2b-it"
  layer: 10
  component: "res"
  seed: 42
  use_bf16: true
  output_length: 128
  models:
    DiffMean:
      batch_size: 32
      n_epochs: 1
      binarize_dataset: true
      low_rank_dimension: 1
inference:
  use_bf16: true
  models: ["DiffMean"]
  model_name: "google/gemma-2-2b-it"
  # latent related params
  output_length: 128
  latent_num_of_examples: 36
  latent_batch_size: 16
  # steering related params
  steering_intervention_type: "addition" # clamping
  steering_model_name: "google/gemma-2-2b-it"
  steering_datasets: ["AlpacaEval"]
  steering_batch_size: 100
  steering_output_length: 128
  steering_layers: [10]
  steering_num_of_examples: 10 # number of examples per concept and per factor
  steering_factors: [0.2, 0.6, 1.0, 2.0, 3.0] # number of steering factors per example
  # master data dir is shared across all jobs.
  master_data_dir: "axbench/data"
  seed: 42
  lm_model: "gpt-4o-mini"
  # generation related params
  temperature: 1.0
evaluate:
  models: ["DiffMean"]
  latent_evaluators: [
    "AUCROCEvaluator",
    "HardNegativeEvaluator",
  ]
  steering_evaluators: [
    # "PerplexityEvaluator", 
    "LMJudgeEvaluator",
  ]
  winrate_split_ratio: 0.5 # this is for steering only, we use a separate partition for factor selection.
  # Number of processes to run in parallel for steering evaluation.
  num_of_workers: 32
  lm_model: "gpt-4o-mini"
  run_winrate: false
  winrate_baseline: "PromptSteering"
  # master data dir is shared across all jobs.
  master_data_dir: "axbench/data"
