data_dir: "axbench/demo/generate"
dump_dir: "axbench/demo"

# interpreting model
model_name: "google/gemma-2-2b"
layer: 20
component: "res"

# training params (only enabled models you want to test)
models: 
  ReAX:
    batch_size: 6
    n_epochs: 12
    k_latent_null_loss: 1
    lr: 0.003
    coeff_l1_loss_null: 0.05
    coeff_l1_loss: 0.001
  LinearProbe:
    batch_size: 6
    n_epochs: 12
    lr: 0.003
  L1LinearProbe:
    batch_size: 6
    n_epochs: 12
    k_latent_null_loss: 1
    lr: 0.003
    coeff_l1_loss_null: 0.5
    coeff_l1_loss: 0.1